
        package model.python.alias

        import model.python.builtins.identifier


        // This file is generated by :python:ast:generator module, entry point in main.kt.
// Please don't modify it by and and commit, and instead modify the generation logic.


        sealed class alias()
        
        
        data class aliasImpl(val name: identifier, val asname: identifier?)
            : alias() 
        
    