
        package model.python.arguments

        import model.python.arg.arg
        import model.python.expr.expr


        // This file is generated by :python:ast:generator module, entry point in main.kt.
// Please don't modify it by and and commit, and instead modify the generation logic.


        sealed class arguments()
        
        
        data class argumentsImpl(val posonlyargs: kotlin.collections.List<arg>, val args: kotlin.collections.List<arg>, val vararg: arg?, val kwonlyargs: kotlin.collections.List<arg>, val kw_defaults: kotlin.collections.List<expr>, val kwarg: arg?, val defaults: kotlin.collections.List<expr>)
            : arguments() 
        
    