
        package model.python.comprehension

        import model.python.builtins.int
        import model.python.expr.expr


        // This file is generated by :python:ast:generator module, entry point in main.kt.
// Please don't modify it by and and commit, and instead modify the generation logic.


        sealed class comprehension()
        
        
        data class comprehensionImpl(val target: expr, val iter: expr, val ifs: kotlin.collections.List<expr>, val is_async: int)
            : comprehension() 
        
    