
        package model.python.keyword

        import model.python.builtins.identifier
        import model.python.expr.expr


        // This file is generated by :python:ast:generator module, entry point in main.kt.
// Please don't modify it by and and commit, and instead modify the generation logic.


        sealed class keyword()
        
        
        data class keywordImpl(val arg: identifier?, val value: expr)
            : keyword() 
        
    