
        package model.python.type_ignore

        import model.python.builtins.string


        // This file is generated by :python:ast:generator module, entry point in main.kt.
// Please don't modify it by and and commit, and instead modify the generation logic.


        sealed class type_ignore()
        
        
        data class TypeIgnore(val tag: string)
            : type_ignore() 
        
    